# Generated by Django 4.2 on 2023-04-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('education', models.CharField(max_length=50, verbose_name='Образование')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245, verbose_name='Название услуги')),
                ('price', models.IntegerField(default=999, verbose_name='Цена')),
                ('description', models.TextField(max_length=245, verbose_name='Описание')),
                ('category', models.ManyToManyField(to='vetsite.category')),
            ],
        ),
    ]
