# Generated by Django 4.2 on 2023-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0003_doctors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(default='defaultimage.png', height_field=100, upload_to='media/', verbose_name='Фотографии', width_field=100),
        ),
    ]
