# Generated by Django 4.2 on 2023-04-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0005_alter_doctors_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='category',
        ),
        migrations.RemoveField(
            model_name='services',
            name='category',
        ),
        migrations.AddField(
            model_name='doctors',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vetsite.category'),
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='vetsite.category'),
        ),
    ]
