# Generated by Django 4.2 on 2023-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
