# Generated by Django 4.2 on 2023-05-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0008_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
    ]
