# Generated by Django 4.2 on 2023-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0009_remove_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
