# Generated by Django 4.2 on 2023-05-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0010_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
