# Generated by Django 4.2 on 2023-05-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetsite', '0011_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='defaultimage.png', upload_to='media/', verbose_name='Изображение'),
        ),
    ]
